/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nafarra;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AdminPage extends javax.swing.JFrame {

    private static Connection connection;
    /**
     * Creates new form AdminPage
     */
    CardLayout cardLayout;
    public AdminPage() {
        initComponents();
        connectToDB();
        cardLayout = (CardLayout)(cardPanel.getLayout());
    }
    
    public static void connectToDB() {
        String url = "jdbc:sqlserver://localhost:1433; databaseName=nafarra; integratedSecurity=true;";
        try {
            connection = DriverManager.getConnection(url);
            System.out.println("Connected to Database");

        } catch (SQLException throwables) {
            System.out.println("Oops, an error has occured");
            throwables.printStackTrace();
        }
    }
    
    public void populateJTable(String query, javax.swing.JTable table) {
        try {
            Statement statement = connection.createStatement();
            statement.executeQuery(query);
            ResultSet rs = statement.executeQuery(query);
            ResultSetMetaData mtdt = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel)table.getModel();

            Vector<String> columnNames = new Vector<String>();
            int columnCount = mtdt.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(mtdt.getColumnName(i));
            }

            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
            tm.setDataVector(data, columnNames);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }
    
    public void populateJTable4(String query) {
        try {
            Statement statement = connection.createStatement();
            statement.executeQuery(query);
            ResultSet rs = statement.executeQuery(query);
            ResultSetMetaData mtdt = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel)custTable.getModel();

            Vector<String> columnNames = new Vector<String>();
            int columnCount = mtdt.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(mtdt.getColumnName(i));
            }

            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
            tm.setDataVector(data, columnNames);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        cardCreateOrder = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zipCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prov = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        delivType = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        custPhone = new javax.swing.JTextField();
        makeOrderButton = new javax.swing.JButton();
        cardReadOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        orderSearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        orderSearchButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        orderTable3 = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        cardUpdateOrder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        orderID = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        newStatus = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        cardDeleteOrder = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        orderIDtoDelete = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        cardAddEmployee = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        empNameToAdd = new javax.swing.JTextField();
        empSexToAdd = new javax.swing.JComboBox<>();
        empSalaryToAdd = new javax.swing.JTextField();
        empNumToAdd = new javax.swing.JTextField();
        empBdateToAdd = new javax.swing.JTextField();
        addEmpButton = new javax.swing.JButton();
        empBranchToAdd = new javax.swing.JComboBox<>();
        empDivToAdd = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cardUpdateEmployee = new javax.swing.JPanel();
        cardUpdate = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        empIDtoUpdate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        empSalaryToUpdate = new javax.swing.JTextField();
        updateEmpButton = new javax.swing.JButton();
        cardDelete = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        empIDtoDelete = new javax.swing.JTextField();
        deleteEmpButton = new javax.swing.JButton();
        cardCheckCust = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        custNameToCheck = new javax.swing.JTextField();
        checkCustButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        cardCheckEmployee = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        empNameToCheck = new javax.swing.JTextField();
        checkEmpButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField5.setText("jTextField5");

        jLabel14.setText("jLabel14");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));
        setSize(new java.awt.Dimension(800, 450));

        jPanel1.setBackground(new java.awt.Color(97, 140, 124));

        jPanel2.setBackground(new java.awt.Color(233, 235, 221));

        jButton1.setBackground(new java.awt.Color(206, 217, 126));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(97, 140, 124));
        jButton1.setText("BUAT ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(206, 217, 126));
        jButton2.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(97, 140, 124));
        jButton2.setText("CARI ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(206, 217, 126));
        jButton3.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(97, 140, 124));
        jButton3.setText("UPDATE STATUS ORDER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(206, 217, 126));
        jButton4.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(97, 140, 124));
        jButton4.setText("HAPUS ORDER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(206, 217, 126));
        jButton6.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(97, 140, 124));
        jButton6.setText("TAMBAH PEGAWAI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(206, 217, 126));
        jButton7.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(97, 140, 124));
        jButton7.setText("UPDATE PEGAWAI");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(206, 217, 126));
        jButton8.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(97, 140, 124));
        jButton8.setText("CEK CUSTOMER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(206, 217, 126));
        jButton5.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(97, 140, 124));
        jButton5.setText("CEK PEGAWAI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel.setBackground(new java.awt.Color(233, 235, 221));
        cardPanel.setLayout(new java.awt.CardLayout());

        cardCreateOrder.setBackground(new java.awt.Color(233, 235, 221));

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(97, 140, 124));
        jLabel13.setText("BUAT ORDER");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(97, 140, 124));
        jLabel3.setText("JALAN");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 140, 124));
        jLabel7.setText("NO. RUMAH");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 140, 124));
        jLabel8.setText("KODE POS");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(97, 140, 124));
        jLabel9.setText("KOTA");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(97, 140, 124));
        jLabel10.setText("PROVINSI");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(97, 140, 124));
        jLabel11.setText("TIPE");

        delivType.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        delivType.setForeground(new java.awt.Color(97, 140, 124));
        delivType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULER", "EXPRESS" }));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(97, 140, 124));
        jLabel12.setText("NO. TELP CUSTOMER");

        makeOrderButton.setBackground(new java.awt.Color(206, 217, 126));
        makeOrderButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        makeOrderButton.setForeground(new java.awt.Color(97, 140, 124));
        makeOrderButton.setText("BUAT");
        makeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardCreateOrderLayout = new javax.swing.GroupLayout(cardCreateOrder);
        cardCreateOrder.setLayout(cardCreateOrderLayout);
        cardCreateOrderLayout.setHorizontalGroup(
            cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCreateOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCreateOrderLayout.createSequentialGroup()
                        .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(delivType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardCreateOrderLayout.createSequentialGroup()
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(cardCreateOrderLayout.createSequentialGroup()
                                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(cardCreateOrderLayout.createSequentialGroup()
                                        .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardCreateOrderLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabel10))
                                            .addComponent(stName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stNum, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(177, Short.MAX_VALUE))
                    .addGroup(cardCreateOrderLayout.createSequentialGroup()
                        .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        cardCreateOrderLayout.setVerticalGroup(
            cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCreateOrderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(21, 21, 21)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delivType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCreateOrderLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(makeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        cardPanel.add(cardCreateOrder, "cardCreateOrder");

        cardReadOrder.setBackground(new java.awt.Color(233, 235, 221));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 140, 124));
        jLabel4.setText("CEK ORDER");

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(97, 140, 124));
        jLabel15.setText("ORDER ID");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(orderTable);

        orderSearchButton.setBackground(new java.awt.Color(206, 217, 126));
        orderSearchButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        orderSearchButton.setForeground(new java.awt.Color(97, 140, 124));
        orderSearchButton.setText("CARI");
        orderSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSearchButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(97, 140, 124));
        jLabel19.setText("ORDER STATUS");

        orderTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(orderTable2);

        orderTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(orderTable3);

        jLabel36.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(97, 140, 124));
        jLabel36.setText("ORDER ITEM");

        javax.swing.GroupLayout cardReadOrderLayout = new javax.swing.GroupLayout(cardReadOrder);
        cardReadOrder.setLayout(cardReadOrderLayout);
        cardReadOrderLayout.setHorizontalGroup(
            cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReadOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardReadOrderLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)
                        .addComponent(orderSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardReadOrderLayout.createSequentialGroup()
                                .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cardReadOrderLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardReadOrderLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(191, 191, 191)))
                                .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        cardReadOrderLayout.setVerticalGroup(
            cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReadOrderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(orderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardReadOrderLayout.createSequentialGroup()
                        .addGroup(cardReadOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        cardPanel.add(cardReadOrder, "cardReadOrder");

        cardUpdateOrder.setBackground(new java.awt.Color(233, 235, 221));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(97, 140, 124));
        jLabel5.setText("UPDATE STATUS ORDER");

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(97, 140, 124));
        jLabel16.setText("ID ORDER");

        updateButton.setBackground(new java.awt.Color(206, 217, 126));
        updateButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        updateButton.setForeground(new java.awt.Color(97, 140, 124));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(97, 140, 124));
        jLabel17.setText("STATUS BARU");

        jLabel18.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(97, 140, 124));
        jLabel18.setText("ID PENANGGUNG JAWAB");

        javax.swing.GroupLayout cardUpdateOrderLayout = new javax.swing.GroupLayout(cardUpdateOrder);
        cardUpdateOrder.setLayout(cardUpdateOrderLayout);
        cardUpdateOrderLayout.setHorizontalGroup(
            cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUpdateOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(cardUpdateOrderLayout.createSequentialGroup()
                        .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(36, 36, 36)
                        .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(orderID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardUpdateOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        cardUpdateOrderLayout.setVerticalGroup(
            cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUpdateOrderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(76, 76, 76)
                .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(orderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardUpdateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        cardPanel.add(cardUpdateOrder, "cardUpdateOrder");

        cardDeleteOrder.setBackground(new java.awt.Color(233, 235, 221));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(97, 140, 124));
        jLabel6.setText("HAPUS ORDER");

        jLabel20.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(97, 140, 124));
        jLabel20.setText("ID ORDER");

        deleteButton.setBackground(new java.awt.Color(206, 217, 126));
        deleteButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(97, 140, 124));
        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardDeleteOrderLayout = new javax.swing.GroupLayout(cardDeleteOrder);
        cardDeleteOrder.setLayout(cardDeleteOrderLayout);
        cardDeleteOrderLayout.setHorizontalGroup(
            cardDeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDeleteOrderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardDeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(cardDeleteOrderLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderIDtoDelete)))
                .addGap(26, 26, 26)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        cardDeleteOrderLayout.setVerticalGroup(
            cardDeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDeleteOrderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(cardDeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(orderIDtoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        cardPanel.add(cardDeleteOrder, "cardDeleteOrder");

        cardAddEmployee.setBackground(new java.awt.Color(233, 235, 221));

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(97, 140, 124));
        jLabel21.setText("TAMBAH PEGAWAI");

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(97, 140, 124));
        jLabel22.setText("CABANG");

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(97, 140, 124));
        jLabel23.setText("NAMA");

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(97, 140, 124));
        jLabel24.setText("JENIS KELAMIN");

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(97, 140, 124));
        jLabel25.setText("GAJI");

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(97, 140, 124));
        jLabel26.setText("TANGGAL LAHIR");

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(97, 140, 124));
        jLabel27.setText("NO. TELP");

        empSexToAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        addEmpButton.setBackground(new java.awt.Color(206, 217, 126));
        addEmpButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        addEmpButton.setForeground(new java.awt.Color(97, 140, 124));
        addEmpButton.setText("TAMBAH");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });

        empBranchToAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALANG", "JAKARTA", "BANDUNG" }));

        empDivToAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUST. SERVICE", "LOGISTIC", "COURIER", "ADMINISTRATION" }));

        jLabel35.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(97, 140, 124));
        jLabel35.setText("DIVISI");

        jLabel37.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(97, 140, 124));
        jLabel37.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout cardAddEmployeeLayout = new javax.swing.GroupLayout(cardAddEmployee);
        cardAddEmployee.setLayout(cardAddEmployeeLayout);
        cardAddEmployeeLayout.setHorizontalGroup(
            cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAddEmployeeLayout.createSequentialGroup()
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(empBdateToAdd))
                            .addComponent(jLabel21)
                            .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27))
                                .addGap(24, 24, 24)
                                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empSexToAdd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(empSalaryToAdd)
                                    .addComponent(empNumToAdd)
                                    .addComponent(empNameToAdd))))
                        .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel35))
                                .addGap(18, 18, 18)
                                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(empDivToAdd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(empBranchToAdd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                            .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel37)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        cardAddEmployeeLayout.setVerticalGroup(
            cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAddEmployeeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(empBranchToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empDivToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35))
                    .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empSexToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empSalaryToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(9, 9, 9)
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(empBdateToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNumToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(67, 67, 67)
                .addComponent(addEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        cardPanel.add(cardAddEmployee, "cardAddEmployee");

        cardUpdateEmployee.setBackground(new java.awt.Color(97, 140, 124));

        cardUpdate.setBackground(new java.awt.Color(233, 235, 221));

        jLabel28.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(97, 140, 124));
        jLabel28.setText("UPDATE PEGAWAI");

        jLabel29.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(97, 140, 124));
        jLabel29.setText("ID PEGAWAI");

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(97, 140, 124));
        jLabel30.setText("GAJI BARU");

        updateEmpButton.setBackground(new java.awt.Color(206, 217, 126));
        updateEmpButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        updateEmpButton.setForeground(new java.awt.Color(97, 140, 124));
        updateEmpButton.setText("UPDATE");
        updateEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardUpdateLayout = new javax.swing.GroupLayout(cardUpdate);
        cardUpdate.setLayout(cardUpdateLayout);
        cardUpdateLayout.setHorizontalGroup(
            cardUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(cardUpdateLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(cardUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empIDtoUpdate)
                    .addComponent(empSalaryToUpdate))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        cardUpdateLayout.setVerticalGroup(
            cardUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUpdateLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel28)
                .addGap(24, 24, 24)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empIDtoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empSalaryToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(updateEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardDelete.setBackground(new java.awt.Color(233, 235, 221));

        jLabel31.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(97, 140, 124));
        jLabel31.setText("HAPUS PEGAWAI");

        jLabel32.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(97, 140, 124));
        jLabel32.setText("ID PEGAWAI");

        deleteEmpButton.setBackground(new java.awt.Color(206, 217, 126));
        deleteEmpButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        deleteEmpButton.setForeground(new java.awt.Color(97, 140, 124));
        deleteEmpButton.setText("HAPUS");
        deleteEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardDeleteLayout = new javax.swing.GroupLayout(cardDelete);
        cardDelete.setLayout(cardDeleteLayout);
        cardDeleteLayout.setHorizontalGroup(
            cardDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDeleteLayout.createSequentialGroup()
                .addGroup(cardDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardDeleteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(cardDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empIDtoDelete))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        cardDeleteLayout.setVerticalGroup(
            cardDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDeleteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel31)
                .addGap(44, 44, 44)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empIDtoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(deleteEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardUpdateEmployeeLayout = new javax.swing.GroupLayout(cardUpdateEmployee);
        cardUpdateEmployee.setLayout(cardUpdateEmployeeLayout);
        cardUpdateEmployeeLayout.setHorizontalGroup(
            cardUpdateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUpdateEmployeeLayout.createSequentialGroup()
                .addComponent(cardUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardUpdateEmployeeLayout.setVerticalGroup(
            cardUpdateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cardPanel.add(cardUpdateEmployee, "cardUpdateEmployee");

        cardCheckCust.setBackground(new java.awt.Color(233, 235, 221));

        jLabel33.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(97, 140, 124));
        jLabel33.setText("CEK CUSTOMER");

        jLabel34.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(97, 140, 124));
        jLabel34.setText("NAMA CUSTOMER");

        checkCustButton.setBackground(new java.awt.Color(206, 217, 126));
        checkCustButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        checkCustButton.setForeground(new java.awt.Color(97, 140, 124));
        checkCustButton.setText("CEK");
        checkCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCustButtonActionPerformed(evt);
            }
        });

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(custTable);

        javax.swing.GroupLayout cardCheckCustLayout = new javax.swing.GroupLayout(cardCheckCust);
        cardCheckCust.setLayout(cardCheckCustLayout);
        cardCheckCustLayout.setHorizontalGroup(
            cardCheckCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardCheckCustLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardCheckCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(cardCheckCustLayout.createSequentialGroup()
                        .addGroup(cardCheckCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(custNameToCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        cardCheckCustLayout.setVerticalGroup(
            cardCheckCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCheckCustLayout.createSequentialGroup()
                .addGroup(cardCheckCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCheckCustLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel33)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custNameToCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardCheckCustLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(checkCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        cardPanel.add(cardCheckCust, "cardCheckCust");

        cardCheckEmployee.setBackground(new java.awt.Color(233, 235, 221));

        jLabel38.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(97, 140, 124));
        jLabel38.setText("CEK PEGAWAI");

        jLabel39.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(97, 140, 124));
        jLabel39.setText("NAMA PEGAWAI");

        checkEmpButton.setBackground(new java.awt.Color(206, 217, 126));
        checkEmpButton.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        checkEmpButton.setForeground(new java.awt.Color(97, 140, 124));
        checkEmpButton.setText("CEK");
        checkEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmpButtonActionPerformed(evt);
            }
        });

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(empTable);

        javax.swing.GroupLayout cardCheckEmployeeLayout = new javax.swing.GroupLayout(cardCheckEmployee);
        cardCheckEmployee.setLayout(cardCheckEmployeeLayout);
        cardCheckEmployeeLayout.setHorizontalGroup(
            cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCheckEmployeeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel38)
                        .addGroup(cardCheckEmployeeLayout.createSequentialGroup()
                            .addGroup(cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel39)
                                .addComponent(empNameToCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        cardCheckEmployeeLayout.setVerticalGroup(
            cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCheckEmployeeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel38)
                .addGap(27, 27, 27)
                .addGroup(cardCheckEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardCheckEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empNameToCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        cardPanel.add(cardCheckEmployee, "cardCheckEmployee");

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 235, 221));
        jLabel1.setText("NAFARRA");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 235, 221));
        jLabel2.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardCreateOrder");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardReadOrder");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardUpdateOrder");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardDeleteOrder");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void orderSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSearchButtonActionPerformed
        // TODO add your handling code here:
        try {
            String inputName = orderSearch.getText();
            String sql1 = "exec cetakOrder '" + inputName +"'";
            String sql2 = "exec cetakStatusAdmin '" + inputName + "'";
            String sql3 = "exec cetakItem '"+ inputName + "'";
            populateJTable(sql1, orderTable);
            populateJTable(sql2, orderTable2);
            populateJTable(sql3, orderTable3);
            if(orderTable.getRowCount()==0)JOptionPane.showMessageDialog(this, "Data tidak ditemukan!","Search Error",
    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pencarian Error!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_orderSearchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            String query = "INSERT INTO Status1 VALUES ('" + java.time.LocalDate.now() + "','" + java.time.LocalTime.now() 
                    + "','" + orderID.getText() + "','" + newStatus.getText() + "','" + empID.getText() +"')";
            Statement statement = connection.createStatement();
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin menambahkan \""+newStatus.getText()+"\" pada "+orderID.getText()+
                        " dengan penanggung jawab "+getNamaEmp(empID.getText())+"?", 
                "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Status order berhasil ditambahkan!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Status order batal ditambahkan!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Status order gagal ditambahkan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            Statement statement = connection.createStatement();
            String query = "DELETE FROM Order1 WHERE order_id = '" + orderIDtoDelete.getText() + "'";
            String cari = "select order_id from Order1 where order_id ='"+orderIDtoDelete.getText()+"'";
            ResultSet rs = statement.executeQuery(cari);
            String hasil = "";
            while(rs.next()){
                hasil = rs.getString("order_id");
            }
            if(hasil.equals("")){
                JOptionPane.showMessageDialog(this, "Data order tidak ditemukan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin menghapus "+orderIDtoDelete.getText()+"?", "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Data order berhasil dihapus!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Data order batal dihapus!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
            orderIDtoDelete.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data order tidak ditemukan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardAddEmployee");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            String query = "exec addEmployee '" + empNameToAdd.getText() + "','" + empSexToAdd.getSelectedItem() + "','" 
                    + empSalaryToAdd.getText() + "','" + empBdateToAdd.getText() + "','" + empNumToAdd.getText() + "','" + empBranchToAdd.getSelectedItem() 
                    + "','" + empDivToAdd.getSelectedItem() + "'";
            Statement statement = connection.createStatement();
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin menambahkan "+empNameToAdd.getText()+"?", "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Data pegawai berhasil ditambahkan!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Data pegawai batal ditambahkan!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
            empNameToAdd.setText(""); empSalaryToAdd.setText(""); empBdateToAdd.setText(""); empNumToAdd.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data pegawai gagal ditambahkan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_addEmpButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardUpdateEmployee");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void updateEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            String query = "UPDATE Employee SET salary = " + empSalaryToUpdate.getText() + "WHERE emp_id = '" + empIDtoUpdate.getText() + "'";
            Statement statement = connection.createStatement();
            String cari = "select emp_id from Employee where emp_id ='"+empIDtoUpdate.getText()+"'";
            ResultSet rs = statement.executeQuery(cari);
            String hasil = "";
            while(rs.next()){
                hasil = rs.getString("emp_id");
            }
            if(hasil.equals("")){
                JOptionPane.showMessageDialog(this, "Data pegawai tidak ditemukan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin mengubah gaji "+getNamaEmp(empIDtoUpdate.getText())+"?", "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Update gaji berhasil!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Update gaji dibatalkan!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
            empIDtoUpdate.setText(""); empSalaryToUpdate.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gaji gagal diubah!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateEmpButtonActionPerformed

    private void deleteEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            String query = "DELETE FROM Employee WHERE emp_id = '" + empIDtoDelete.getText() + "'";
            Statement statement = connection.createStatement();
            String cari = "select emp_id from Employee where emp_id ='"+empIDtoUpdate.getText()+"'";
            ResultSet rs = statement.executeQuery(cari);
            String hasil = "";
            while(rs.next()){
                hasil = rs.getString("emp_id");
            }
            if(hasil.equals("")){
                JOptionPane.showMessageDialog(this, "Data pegawai tidak ditemukan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin menghapus data "+getNamaEmp(empIDtoDelete.getText())+"?", "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Penghapusan data karyawan berhasil!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Penghapusan data karyawan dibatalkan!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
            empIDtoDelete.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data pegawai gagal dihapus!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteEmpButtonActionPerformed
    
    private String getNamaEmp(String id){
        String nama="";
        try{
            String query = "SELECT name from Employee where emp_id = '"+id+"'";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()){
                nama = rs.getString("name");
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return nama;
    }
    
    private void checkCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCustButtonActionPerformed
        // TODO add your handling code here:
        try {
            String parameter = custNameToCheck.getText();
            String sql1 = "exec cetakCustomer '"+parameter+"'";
            populateJTable(sql1,custTable);
            if(custTable.getRowCount()==0)JOptionPane.showMessageDialog(this, "Data tidak ditemukan!","Search Error",
            JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Customer tidak ditemukan!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_checkCustButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardCheckCust");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void makeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrderButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            String jnsKirim = delivType.getSelectedItem().equals("REGULER")? "REG":"EXP";
            String query = "exec addOrder '" + stName.getText() + "','" + stNum.getText() + "','" 
                    + zipCode.getText() + "','" + city.getText() + "','" + java.time.LocalDate.now() + "','" + custPhone.getText() 
                    + "','" + jnsKirim + "','" + prov.getText() + "'";
            Statement statement = connection.createStatement();
            int input = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin membuat order baru?", "Select an Option...",JOptionPane.OK_CANCEL_OPTION);
            statement.executeUpdate(query);
            if(input == 0){
                connection.commit();
                JOptionPane.showMessageDialog(this, "Order berhasil dibuat!");
            }
            else{
                connection.rollback();
                JOptionPane.showMessageDialog(this, "Order gagal dibuat!","Error...",
                JOptionPane.ERROR_MESSAGE);
            }
            stName.setText(""); stNum.setText(""); zipCode.setText(""); city.setText(""); custPhone.setText(""); prov.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Order gagal dibuat!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_makeOrderButtonActionPerformed

    private void checkEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmpButtonActionPerformed
        // TODO add your handling code here:
        try {
            String parameter = empNameToCheck.getText();
            String sql1 = "SELECT * FROM Employee WHERE name LIKE '%" +parameter+ "%'";
            populateJTable(sql1,empTable);
            if(empTable.getRowCount()==0)JOptionPane.showMessageDialog(this, "Data tidak ditemukan!","Search Error",
            JOptionPane.ERROR_MESSAGE);
            empNameToCheck.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pencarian data pegawai error!","Error...",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_checkEmpButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "cardCheckEmployee");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println(java.time.LocalDate.now());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpButton;
    private javax.swing.JPanel cardAddEmployee;
    private javax.swing.JPanel cardCheckCust;
    private javax.swing.JPanel cardCheckEmployee;
    private javax.swing.JPanel cardCreateOrder;
    private javax.swing.JPanel cardDelete;
    private javax.swing.JPanel cardDeleteOrder;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cardReadOrder;
    private javax.swing.JPanel cardUpdate;
    private javax.swing.JPanel cardUpdateEmployee;
    private javax.swing.JPanel cardUpdateOrder;
    private javax.swing.JButton checkCustButton;
    private javax.swing.JButton checkEmpButton;
    private javax.swing.JTextField city;
    private javax.swing.JTextField custNameToCheck;
    private javax.swing.JTextField custPhone;
    private javax.swing.JTable custTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteEmpButton;
    private javax.swing.JComboBox<String> delivType;
    private javax.swing.JTextField empBdateToAdd;
    private javax.swing.JComboBox<String> empBranchToAdd;
    private javax.swing.JComboBox<String> empDivToAdd;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empIDtoDelete;
    private javax.swing.JTextField empIDtoUpdate;
    private javax.swing.JTextField empNameToAdd;
    private javax.swing.JTextField empNameToCheck;
    private javax.swing.JTextField empNumToAdd;
    private javax.swing.JTextField empSalaryToAdd;
    private javax.swing.JTextField empSalaryToUpdate;
    private javax.swing.JComboBox<String> empSexToAdd;
    private javax.swing.JTable empTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton makeOrderButton;
    private javax.swing.JTextField newStatus;
    private javax.swing.JTextField orderID;
    private javax.swing.JTextField orderIDtoDelete;
    private javax.swing.JTextField orderSearch;
    private javax.swing.JButton orderSearchButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable orderTable2;
    private javax.swing.JTable orderTable3;
    private javax.swing.JTextField prov;
    private javax.swing.JTextField stName;
    private javax.swing.JTextField stNum;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateEmpButton;
    private javax.swing.JTextField zipCode;
    // End of variables declaration//GEN-END:variables
}
