/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nafarra;


import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Query extends javax.swing.JFrame {

    private Connection connection;
    /**
     * Creates new form Query
     */
    public Query() {
        connectToDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTable = new javax.swing.JTable();
        query1Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        query2Btn = new javax.swing.JButton();
        query3Btn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 235, 221));

        queryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(queryTable);

        query1Btn.setBackground(new java.awt.Color(206, 217, 126));
        query1Btn.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        query1Btn.setForeground(new java.awt.Color(97, 140, 124));
        query1Btn.setText("QUERY 1");
        query1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query1BtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(97, 140, 124));
        jLabel1.setText("QUERY");

        query2Btn.setBackground(new java.awt.Color(206, 217, 126));
        query2Btn.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        query2Btn.setForeground(new java.awt.Color(97, 140, 124));
        query2Btn.setText("QUERY 2");
        query2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query2BtnActionPerformed(evt);
            }
        });

        query3Btn.setBackground(new java.awt.Color(206, 217, 126));
        query3Btn.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        query3Btn.setForeground(new java.awt.Color(97, 140, 124));
        query3Btn.setText("QUERY 3");
        query3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query3BtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(206, 217, 126));
        backBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        backBtn.setForeground(new java.awt.Color(97, 140, 124));
        backBtn.setText("KEMBALI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(query1Btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(query2Btn)
                        .addGap(38, 38, 38)
                        .addComponent(query3Btn))
                    .addComponent(jLabel1))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(query1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(query2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(query3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void query1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query1BtnActionPerformed
        // TODO add your handling code here:
        String query = "EXEC Query1";
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            ResultSetMetaData metaData = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel)queryTable.getModel();
            
            Vector<String> columnNames = new Vector<String>();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }

            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
            tm.setDataVector(data, columnNames);
            JOptionPane.showMessageDialog(this, "Execute Query 1 Berhasil!");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_query1BtnActionPerformed

    private void query2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query2BtnActionPerformed
        // TODO add your handling code here:
        String query = "EXEC Query2";
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            ResultSetMetaData metaData = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel)queryTable.getModel();
            
            Vector<String> columnNames = new Vector<String>();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }

            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
            tm.setDataVector(data, columnNames);
            JOptionPane.showMessageDialog(this, "Execute Query 2 Berhasil!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_query2BtnActionPerformed

    private void query3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query3BtnActionPerformed
        // TODO add your handling code here:
        String query = "EXEC Query3";
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            ResultSetMetaData metaData = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel)queryTable.getModel();
            
            Vector<String> columnNames = new Vector<String>();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }

            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
            tm.setDataVector(data, columnNames);
            JOptionPane.showMessageDialog(this, "Execute Query 3 Berhasil!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_query3BtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LandingPage landingPage = new LandingPage();
        landingPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    
    private void connectToDB() {
        String url = "jdbc:sqlserver://localhost:1433; databaseName=nafarra; integratedSecurity=true;";
        try {
            connection = DriverManager.getConnection(url);
            System.out.println("Connected to Database");

        } catch (SQLException throwables) {
            System.out.println("Oops, an error has occured");
            throwables.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Query().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton query1Btn;
    private javax.swing.JButton query2Btn;
    private javax.swing.JButton query3Btn;
    private javax.swing.JTable queryTable;
    // End of variables declaration//GEN-END:variables
}
